language: cpp
sudo: false
dist: trusty
compiler:
- g++
os:
- linux

branches:
  only:
  - master

script:
  - mkdir out
  - cmake -DOpenCV_Enable=ON .


notifications:
  email:
    - ericliu612@gmail.com

env:
  global:
  - LANG="en_US.UTF-8"